name = "cloudflare-r2-image-uploader"  # Name of your Pages project

[build]
  command = "npm install"  # Optional: Only if you have a build step
  publish_dir = "frontend"  # This should point to your static frontend folder
  pages_build_output_dir = "frontend"  # Output directory for Pages (use the correct folder)

[[env]]
name = "production"
route = "https://cloudflare-r2-image-uploader.pages.dev/*"  # Cloudflare Pages URL for your frontend
