name = "dpp1"
type = "javascript"
compatibility_date = "2025-03-12"  # Add this line to specify the compatibility date
[build]
  command = "npm install"
  worker = "./backend/src/index.js"  # Path to the Worker file
  publish_dir = "frontend"
  pages_build_output_dir = "frontend" 

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "image-uploads"  # Name of your R2 bucket

[[env]]
name = "production"
route = "https://dpp1.burrito-bot.workers.dev/*"  # Your Cloudflare Worker URL

#name = "cloudflare-r2-image-uploader"  # Name of your Pages project

#[build]
#  command = "npm install"  # Optional: Only if you have a build step
#  publish_dir = "frontend"  # This should point to your static frontend folder
#  pages_build_output_dir = "frontend"  # Output directory for Pages (use the correct folder)

#[[env]]
#name = "production"
#route = "https://cloudflare-r2-image-uploader.pages.dev/*"  # Cloudflare Pages URL for your frontend
